### ISSUE TITLE
Low Priority - Add --x-crisis-skip-assert-invariants

### ISSUE THREAD

**Issue by apollodao-dev** [terra-money/mantlemint#35]
**Problem**

When running the first time, its validate the genesis and check for assert every invariants. This can take a huge time and CPU / Memory resources. This also affects the hardware requirements for running the mantlemint server or VM.

**Proposed Solution**
  
To reduce the **start time** on running the first time, we can skip assert invariants ( since the mantlemint is not like a fully lcd validator ) by adding `--x-crisis-skip-assert-invariants` as a parameter.

**Comment by etienne-napoleone** [comment]
Might be already present as per one of the tasks in the release PR https://github.com/terra-money/mantlemint/pull/34#issue-1166121612
But can't see it in the docs

**Comment by hanjukim** [comment]
Isn't it included in the release? I see viper parsing in db/heleveldb/config.go

**Comment by kjessec** [comment]
@apollodao-dev https://github.com/terra-money/mantlemint/pull/36 this should fix it.

**Comment by apollodao-dev** [comment]
@kjessec Hi, I can visually confirm that running with --x-crisis-skip-assert-invariants skip the invariants check on #36 . Thank you!
