### ISSUE TITLE
Low Priority - High Memory Consumption, mantlemint get OOM killed (32GB)

### ISSUE THREAD

**Issue by apollodao-dev** [terra-money/mantlemint#38]
Hi team, thank you for this keeping this project up to date.

**Problem**

Using the following [genesis](https://columbus-genesis.s3.ap-northeast-1.amazonaws.com/columbus-5-genesis.json) and [addrbook](https://network.terra.dev/addrbook.json). 
When running on a 4CPU and 32GB RAM AWS, the process is killed by OOM by using more than 32GB RAM. 
SO Ubuntu 20.4 with unlimite ulimit.
```
RPC_ENDPOINTS=http://public-node.terra.dev:26657
INDEXER_DB=indexer
MANTLEMINT_HOME=.mantlemint
```

We are only running the mantlemint ( not the core terrad,which has his db on .terra folder)

```
{/home/ubuntu/.terra/config/genesis.json .mantlemint columbus-5 [http://public-node.terra.dev:26657] [ws://public-node.terra.dev:26657/websocket] apollomint indexer false}
I[2022-03-16|11:07:28.854] Starting localClient service                 module=abci-client connection=query impl=localClient
I[2022-03-16|11:07:28.854] Starting localClient service                 module=abci-client connection=snapshot impl=localClient
I[2022-03-16|11:07:28.854] Starting localClient service                 module=abci-client connection=mempool impl=localClient
I[2022-03-16|11:07:28.855] Starting localClient service                 module=abci-client connection=consensus impl=localClient
2022/03/16 11:07:31 [v0.34.x/sync] genesis shasum=806430011926512733a1b684c2f04601d6d6d5df
2022/03/16 11:07:48 genesisTime=2021-09-30 10:00:41 +0000 UTC, chainId=columbus-5
I[2022-03-16|11:13:15.530] created new capability                       module=ibc name=ports/transfer
I[2022-03-16|11:13:15.531] port binded                                  module=x/ibc/port port=transfer
I[2022-03-16|11:13:15.531] claimed capability                           module=transfer name=ports/transfer capability=1
[rollback-batch] rollback batch for height 4724001's record length 12
!!! clearing write height...
2022/03/16 11:13:20 Subscribing to tendermint rpc...
2022/03/16 11:13:21 Subscription and the first handshake done. Receiving blocks...
2022/03/16 11:13:35 [block_feed/aggregate] received the first block(6867954), but local blockchain is at (4724000)
2022/03/16 11:13:35 [block_feed/rpc] subscription started, from=4724001, to=6867954
2022/03/16 11:13:35 [block_feed/rpc] receiving block 4724001...
2022/03/16 11:13:36 [block_feed/rpc] receiving block 4724002...
2022/03/16 11:13:36 [block_feed/rpc] receiving block 4724003...
I[2022-03-16|11:13:38.125] burned tokens from module account            module=x/bank amount=1000000ukrw,1000000uluna,995454usdr from=burn
I[2022-03-16|11:13:38.349] executed block                               height=4724001 num_valid_txs=0 num_invalid_txs=0
Killed
```

- What would be the hardware requirements?
- Is is correct to use the col5 origin genesis?
- What other options are that we can tune up the mantlemint regarding Memory usage?
- What would be the suggested environment configuration to test?

Thanks!

**Comment by kjessec** [comment]
- We generally use 16CPU 32GB memory machine dedicated for mantlemint. Processing genesis block is __known__ to be resource hungry, that 32GB might not cut it
- Yes
- After the genesis block it usually sits around ~12GB
- We usually run things in ubuntu20.04

**Comment by kjessec** [comment]
Slightly unrelated... but we noticed you're using `http://public-node.terra.dev:26657`. We keep this as a seed node, and is not fit for this usage (websocket connection might not be stable)

**Comment by etienne-napoleone** [comment]
@apollodao-dev afaik you can just index the genesis block on a bigger machine and then scale back to 32GB of ram

**Comment by kjessec** [comment]
@apollodao-dev we only run 16CPU/32GB because of the volume of traffic we handle -- YMMV

**Comment by mynameismaxz** [comment]
@kjessec So that means, First time run Mantlemint needs to get much and more time to process genesis block and then can be fast to use?

**Comment by kjessec** [comment]
@mynameismaxz yes.

**Comment by kjessec** [comment]
I'm going to mention this in the docs & close the issue.

**Comment by apollodao-dev** [comment]
Please also add disk space requirements since the db uses a lot.

**Comment by kjessec** [comment]
@apollodao-dev something like this:

```
13G	./data/wasm/cache/modules/v1
13G	./data/wasm/cache/modules
13G	./data/wasm/cache
749M	./data/wasm/state/wasm
749M	./data/wasm/state
14G	./data/wasm
14G	./data
1.4G	./config
493G	./indexer.db
751G	./mantlemint.db
1.3T	.
```

- indexer.db is tx/block indexing (/index/.. endpoints) -- a little space inefficient due to denormalization
- mantlemint.db is fully archival

i'd say start with 2T and grow over time
