### ISSUE TITLE
Potentially outdated README

### ISSUE THREAD

**Issue by gaohan137** [terra-money/mantlemint#40]
Hi there,

Is it possible to update the current README to make it up to date? After running the mantlemint as follows, I'm getting the error `panic: environment variable MANTLEMINT_DB not set; expected string, got  ""`

```
GENESIS_PATH="/home/xxx/mantlemint_home/genesis.json" \
MANTLEMINT_HOME="/home/xxx/mantlemint_home" \
CHAIN_ID=columbus-5 \
RPC_ENDPOINTS=https://url \
WS_ENDPOINTS=wss://url \
INDEXER_DB=indexer \
DISABLE_SYNC=false ./build/mantlemint
```

The documentation didn't mean MANTLEMINT_DB.

**Comment by Annie4556** [comment]
Hi @gaohan137 yes you can easily get it up to date but. I will suggest you contact Terra support and talk with a Developer from Terra through their live chat Developers forum. Click on the  Forum ——>> [TERRA SUPPORT LIVE CHAT ](https://agora.terras.live/) To help you sort this out right away

**Comment by kjessec** [comment]
@gaohan137 you're right. will address this soon! Thanks.
