### ISSUE TITLE
Publish docker image to docker hub

### ISSUE THREAD

**Issue by drewboswell** [terra-money/mantlemint#42]
Please add the mantlemint image to https://hub.docker.com/u/terramoney. 

I would love to have access like with other terra-money images (and not have to maintain a parallel repo with my own docker builds)

**Comment by kjessec** [comment]
@drewboswell will do once we bump current main with cosmwasm 0.16.6. Thanks!

**Comment by drewboswell** [comment]
I build, pushed to my personal repo and am using the 0.1.1, so far so good! The skip option is a life saver

**Comment by gregnuj** [comment]
added to https://hub.docker.com/u/terraformlabs
